networks:
    app:
        external: true
services:
    qb:
        container_name: qb
        deploy:
            resources:
                limits:
                    cpus: "0"
                    memory: "0"
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK_SET=022
            - TZ=Asia/Shanghai
            - WEBUI_PORT=8181
            - TORRENTING_PORT=48181
        image: linuxserver/qbittorrent:5.1.0
        labels:
            createdBy: Apps
        networks:
            - app
        ports:
            - 48181:48181
            - 48181:48181/udp
            - 8181:8181
        restart: always
        volumes:
            - ./config:/config
            - /vol2/downloads/qb:/downloads
