networks:
    app:
        external: true

services:
  sun-panel:
    image: "hslr/sun-panel:1.7.0"
    container_name: sun-panel
    volumes:
      - ./conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3002:3002
    restart: always