networks:
    app:
        external: true
services:
    navidrome:
        container_name: navidrome
        deploy:
            resources:
                limits:
                    cpus: "0"
                    memory: "0"
        environment:
            - PUID=1000
            - PGID=1000
        image: deluan/navidrome:0.55.2
        networks:
            - app
        ports:
            - 4533:4533
        restart: always
        volumes:
            - ./data/data:/data
            - /vol2/downloads/qb/yinyue:/music:ro
