networks:
    app:
        external: true
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: always
    networks:
      - app
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: always
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # 请勿删除密钥周围的引号
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN4J32V6YULnxKmD5Y9Bxcsh4DjIOJiUqCe+Tb4W+dLM'